CREATE DATABASE QUESITO;

--CREATES
CREATE TABLE PERFIS (
	ID INT NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	
	CONSTRAINT PK_PERFIS PRIMARY KEY(ID)
); 

CREATE TABLE USUARIOS(
	ID INT NOT NULL AUTO_INCREMENT,
	CPF BIGINT NOT NULL,
	DT_NASCIMENTO DATETIME NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	RG BIGINT NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	ID_PERFIL INT NOT NULL,
	
	CONSTRAINT PK_USUARIOS PRIMARY KEY(ID),
	CONSTRAINT FK_PERFIS FOREIGN KEY(ID_PERFIL) REFERENCES PERFIS(ID)
);

CREATE TABLE ESTADO_CIVIL(
	ID INT NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	
	CONSTRAINT PK_ESTADO_CIVIL PRIMARY KEY(ID)
);

CREATE TABLE REQUERENTES(
	ID INT NOT NULL AUTO_INCREMENT,
	CPF BIGINT NOT NULL,
	DT_NASCIMENTO DATETIME NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(150) NOT NULL,
	COMPLEMENTO VARCHAR(150) NOT NULL,
	LOGRADOURO VARCHAR(250) NOT NULL,
	ID_ESTADO_CIVIL INT NOT NULL,
	NOME VARCHAR(150) NOT NULL,
	PROFISSAO VARCHAR(100) NOT NULL,
	RG BIGINT NOT NULL,
	TEL_CEL BIGINT NOT NULL,
	TEL_RES BIGINT NOT NULL,
	
	CONSTRAINT PK_REQUERENTES PRIMARY KEY(ID),
	CONSTRAINT FK_ESTADO_CIVIL FOREIGN KEY(ID_ESTADO_CIVIL) REFERENCES ESTADO_CIVIL(ID)
);

CREATE TABLE EVENTOS(
	ID INT NOT NULL AUTO_INCREMENT,
	OBM BIGINT NOT NULL,
	DT_EVENTO DATETIME NOT NULL,
	BAIRRO VARCHAR(150) NOT NULL,
	COMPLEMENTO VARCHAR(150) NOT NULL,
	LOGRADOURO VARCHAR(250) NOT NULL,
	ESPECIE_BEM VARCHAR(150) NOT NULL,
	FINALIDADE VARCHAR(150) NOT NULL,
	
	CONSTRAINT PK_EVENTOS PRIMARY KEY(ID)
);

ALTER TABLE EVENTOS 
ADD ESPECIE_BEM VARCHAR(150) NOT NULL;

ALTER TABLE EVENTOS 
ADD FINALIDADE VARCHAR(150) NOT NULL;


CREATE TABLE PROTOCOLOS(
	ID INT NOT NULL AUTO_INCREMENT,
	ID_REQUERENTE INT NOT NULL,
	ID_EVENTO INT NOT NULL,
	ID_USUARIO INT NOT NULL,	
	CONSTRAINT PK_PROTOCOLOS PRIMARY KEY(ID, ID_REQUERENTE,ID_EVENTO),
	CONSTRAINT FK_REQUERENTE FOREIGN KEY(ID_REQUERENTE) REFERENCES REQUERENTES(ID),
	CONSTRAINT FK_EVENTO FOREIGN KEY(ID_EVENTO) REFERENCES EVENTOS(ID),
	CONSTRAINT FK_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID)
);

--INSERTS 
INSERT INTO PERFIS(DESCRICAO)
VALUES('Administrador'), 
	  ('Integrante da Equipe'), 
	  ('Elaborador');
	  
INSERT INTO ESTADO_CIVIL(DESCRICAO)
VALUES('Solteiro(a)'), 
	  ('Casado(a)'), 
	  ('Separado(a)'),
	  ('Divorciado(a)'),
	  ('Viúvo(a)');
